### ISSUE TITLE
Multiple stores with same subdomain showing as the parent domain in dropdown

### ISSUE THREAD

**Issue by big-pixel** [jetrails/magento2-cloudflare#14]
Added this same issue with Jetails and they asked to provide this to you.

**Comment by null93** [comment]
Will look into this as soon as I can.

**Comment by null93** [comment]
Thank you for submitting this issue. It was patched and should be resolved in version 1.2.2

**Comment by big-pixel** [comment]
Ok stay tuned

Justin Seipel
Chief Creative Technology Architect
Big Pixel Studio <https://www.bigpixelstudio.com/> | 610.530.7093
Twitter <http://twitter.com/#!/bigpixelstudio> | Facebook <https://www.facebook.com/pages/Big-Pixel-Studio/137626507322>
