### ISSUE TITLE
Incorrect AJAX Endpoint When Form Keys Are Disabled

### ISSUE THREAD

**Issue by astayart** [jetrails/magento2-cloudflare#56]
Hi, i installed your module to enable cloudflare cache purging from the magento admin, but it does not work. it looks like a magento controller is missing from your module. here is a screen shot of the 404 error when i click the "purge everything" button: 
![Screen Shot 2020-11-24 at 12 02 01 PM](https://user-images.githubusercontent.com/7265208/100133993-1be0aa00-2e4d-11eb-9b56-93040b12afd2.png)

from my knowledge of magento, the router is looking for a file named "Index.php" but none exists in the folder. the full url for the 404 error shown is: http://theinventingmachines.com/admin/cloudflare/api_caching_purgeCache/

this resolves to the folder: vendor/jetrails/magento2-cloudflare/Controller/Adminhtml/Api/Caching/PurgeCache/
but that folder only contains the files:

[astayart: PurgeCache]# ls -1
Everything.php
Hostname.php
Prefix.php
Tag.php
Url.php

Thanks.

**Comment by null93** [comment]
Hey! I can try to help the best I can. I would like to get some more information from you.

- What module version are you using (latest is 1.3.1)
- How did you install the extension (Magento Marketplace, Github, etc)?
- What version of Magento are you running?

**Comment by null93** [comment]
Some other questions that would be useful:

- Is this only happening on "Purge Everything"?
- Did you update recently? Did you try flushing cache?

**Comment by astayart** [comment]
hi, yes we are using 1.3.1 (as reported in the composer.json file, but the magento "module.xml" file is showing "1.1.1")
we installed via composer with: 
COMPOSER_MEMORY_LIMIT=-1 composer require jetrails/magento2-cloudflare:1.3.1

we are using magento commerce 2.4.1.
this also happens when we try to purge specific url's. here is a screenshot of the result for that action: 
![Screen Shot 2020-11-24 at 12 26 36 PM](https://user-images.githubusercontent.com/7265208/100136347-8d6e2780-2e50-11eb-9796-0af354b363c1.png)

not sure what you mean by "update recently", but yes i updated the module just before this test. i did clear the cache and noticed that the "JetRails" menu item was removed from the left nav the config is now under "System::CloudFlare::CloudFlare Dashboard".

**Comment by null93** [comment]
Yeah I noticed that you did not have the JetRails menu item which we did not remove. Also you have "Cloudflare Dashboard | MU Extension" which is not correct either. Let's try to uninstall it completely, reinstall it, flush cache, setup:upgrade.

**Comment by null93** [comment]
I went ahead and installed the module on 2.4.1 with the same command you used and I am not able to replicate your issue. See the screenshot below, and notice that the request URL is different. Were you able to reinstall the module?

<img width="1919" alt="Screen Shot 2020-11-24 at 1 21 14 PM" src="https://user-images.githubusercontent.com/5500199/100141550-3e2bf500-2e58-11eb-97cd-65dbbf49dace.png">

**Comment by null93** [comment]
I was able to replicate your issue by disabling form keys with `magento config:set admin/security/use_form_key 0`.

![image](https://user-images.githubusercontent.com/5500199/100142178-16895c80-2e59-11eb-85ff-23ea8095204c.png)

**Comment by null93** [comment]
Thank you for reporting this issue. Issue should be resolved in 1.3.2, if issue still persists then feel free to reopen this issue.

**Comment by astayart** [comment]
Hi. Thank you for your support. the menu item was moved by one of my developers to the "system" menu upon request of our Project manager. I can confirm that reactivating the form keys resolved the issue. we turned that off upon request of the client, but will revisit for the obvious security implications.
Thanks

**Comment by null93** [comment]
Not a problem, I'm am glad we were able to resolve this issue. Good luck with everything!
