### ISSUE TITLE
Error on dashboard in developer mode "Call to a member function on a non-object"

### ISSUE THREAD

**Issue by choussamaster** [jetrails/magento2-cloudflare#61]
On local environment in developer mode for the first configuration I get Fatal error: Call to a member function on a non-object"
jetrails/magento2-cloudflare/src/app/code/JetRails/Cloudflare/Model/Adminhtml/Api/Overview/Configuration.php
line 43
for the fix please change
`if (!isset ( $response->success ) && $response->success ) {`
to
`if (is_object($response) && !isset ( $response->success ) && $response->success ) {`

**Comment by null93** [comment]
Thank you for taking the time to open this issue! I tried to replicate this issue by running a brand new magento installation (php-7.4 & magento-2.4.2). Unfortunately, I am not able to replicate these results. That being said, I see no reason not to make this change to ensure `$response` is in fact an object. Thanks for bringing this up!
