### ISSUE TITLE
Undefined property: stdClass::$name_servers

### ISSUE THREAD

**Issue by choussamaster** [jetrails/magento2-cloudflare#64]
Hi
In my server log I found this error
Notice: Undefined property: stdClass::$name_servers in /app/vendor/jetrails/magento2-cloudflare/src/app/code/JetRails/Cloudflare/Model/Adminhtml/Api/Dns/CloudflareNameservers.php on line 36

this is the complete trace for it

![cloudflare-error](https://user-images.githubusercontent.com/750352/117869085-a487c100-b29a-11eb-8cab-f204110f6aa2.png)

**Comment by null93** [comment]
Thanks for submitting! This would be related and fixed with #61.
