### ISSUE TITLE
JS Errors on fresh install

### ISSUE THREAD

**Issue by shaunbanton** [jetrails/magento2-cloudflare#83]
I've installed this via composer and I am getting the following Javascript errors

`Uncaught SyntaxError: Invalid regular expression: missing /
(index):14 Uncaught TypeError: require is not a function
    at (index):14:70965
(index):14 Uncaught TypeError: require.config is not a function
    at (index):14:72362
(index):22 Uncaught TypeError: require is not a function
    at (index):22:1
(index):68 Uncaught ReferenceError: requirejs is not defined
    at (index):68:5
(index):74 Uncaught ReferenceError: requirejs is not defined`

Here is how it is displayed also:
![image](https://user-images.githubusercontent.com/36768609/163565404-a81cfd32-7daf-43f3-882d-8209e016eb33.png)

We are on Magento 2.4.2-p2

**Comment by null93** [comment]
Hey!

Sorry to hear you are having issues. I just tried installing 1.3.8 on a fresh install of Magento with php-7.4 with no issues. Version 1.3.8 did include some RegExp changes in #80. But going through the [diff](https://github.com/jetrails/magento2-cloudflare/commit/18ff1982620c1185928985ed0377f2e8514d542c), all of the expressions look valid. Are you able to install 1.3.7 and tell me if you are having the same issue?

**Comment by shaunbanton** [comment]
@null93 I will give it a try. Thank you

**Comment by null93** [comment]
@shaunbanton closing, if you still have an issue please feel free to reopen!
