### ISSUE TITLE
JS Error On Cloudflare Dashboard Page

### ISSUE THREAD

**Issue by LuisF-Salazar** [jetrails/magento2-cloudflare#85]
I've installed this extension on a Magento 2.4.2-p1 Enterprise Cloud instance through Composer. When I go to the Jetrails > Cloudflare Dashboard admin page, I get the following JS errors:

<img width="1282" alt="Screen Shot 2022-06-13 at 8 21 10 AM" src="https://user-images.githubusercontent.com/53788593/173395493-59e63d87-4a90-40b6-aa5b-536481a152fb.png">

The first error comes from this line:

<img width="874" alt="Screen Shot 2022-06-13 at 11 00 51 AM" src="https://user-images.githubusercontent.com/53788593/173395813-d062b142-03e8-4618-bba1-6c26f680f0a2.png">

Which is from `vendor/jetrails/magento2-cloudflare/view/adminhtml/web/js/firewall/access_rules.js` line 214.

<img width="760" alt="Screen Shot 2022-06-13 at 11 07 28 AM" src="https://user-images.githubusercontent.com/53788593/173396921-c7284077-80ec-4994-916b-681fe378085d.png">

This error is only happening on our Magento Cloud instance. It doesn't happen on my local development environment.

Any ideas what could be causing this?

Thanks

**Comment by null93** [comment]
Thanks for opening an issue about this. I am actually working on a fix for this as we speak. It seems to only happen when in production mode and when `dev/js/minify_files` is enabled. Will update this issue with updates as soon as a solution is implemented and a patch is released. Thanks again for taking the time to open an issue.

**Comment by LuisF-Salazar** [comment]
> Thanks for opening an issue about this. I am actually working on a fix for this as we speak. It seems to only happen when in production mode and when `dev/js/minify_files` is enabled. Will update this issue with updates as soon as a solution is implemented and a patch is released. Thanks again for taking the time to open an issue.

Thank you

**Comment by null93** [comment]
There is a fix in place and is being tested right now. Fix will be available in version 1.3.9.

**Comment by null93** [comment]
@LuisF-Salazar Version 1.3.9 has been released which includes this fix. You can find it here: https://github.com/jetrails/magento2-cloudflare/releases/tag/1.3.9. If you downloaded using the Magento Marketplace registry, then it might take a couple days to publish there.

**Comment by LuisF-Salazar** [comment]
@null93 Thank you very much.
